services:
  fastapi-app:
    build: .
    image: llm-benchmark-image
    container_name: fastapi-container
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - rabbitmq
    environment:
      - REDIS_HOST=redis  # Redis hostname as service name
      - REDIS_PORT=6379
      - RABBITMQ_HOST=rabbitmq

  
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python", "worker.py"]  # Run the worker process
    environment:
      - REDIS_HOST=redis
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy

  redis:
    image: "redis:alpine"
    container_name: redis-container
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"   
      - "15672:15672" 
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
